---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# Statistical Hypothesis Testing in R

`SHT` was designed to provide a casket of tools for hypothesis testing procedures ranging from classical to modern techniques.

## Installation

Currently, `SHT` can only be downloaded via github using following commands,
```r
## install.packages("devtools")
## library(devtools)
devtools::install_github("kisungyou/SHT")
```

## List of Available Tests
We categorized available functions by their object of interest for better navigation.

* Notations **$x$** and **$y$** refer to samples. 
* Authors are referred by last names. See the help page of each function for complete references. 
* **$k$-sample** means that the test is checking the _homogeneity_ across multiple samples.
* Function naming convention is {`type of test`.`test name`}, or {`type of test`.`year` `authors`}, where there are two or three authors, we took their initials as abbreviation or simply the last name of the first author otherwise.
* **`usek1d`** and **`useknd`** lets a user to apply any $k$-sample tests for two-sample testings.
* When $\mathbb{R}^p$ notation is used, it denotes **_multivariate_** procedures.

### 0. utilities 
| function name | description |
|---------------| ------------|
| `usek1d`      | apply $k$-sample test method for two univariate samples |
| `useknd`      | apply $k$-sample test method for two multivariate samples |

### 1. tests for univariate mean $\mu \in \mathbb{R}$
| function name | authors| description of $H_0$ |
|-------|------------------------|:----------------|
| `mean1.ttest` | [Student (1908)][1] | $\mu_x ~\{\leq, =, \geq\}~ \mu_0$ (1-sample) |
| `mean2.ttest` | [Student (1908)][1] & [Welch (1947)][2] | $\mu_x ~\{\leq, =, \geq\}~ \mu_y$ (2-sample) |
| `meank.anova` |               -                 | $\mu_1 = \cdots = \mu_k$ ($k$-sample) |

### 2. tests for multivariate mean $\mu \in \mathbb{R}^p$
| function name | authors | description of $H_0$|
|---------------|------------------------|:----------------|
| `mean1.1931Hotelling` | [Hotelling (1931)][3]       | $\mu_x = \mu_0$ (1-sample) |
| `mean1.1958Dempster`  | [Dempster (1958, 1960)][4]  | $\mu_x = \mu_0$ (1-sample) |
| `mean1.1996BS`       | [Bai and Saranadasa (1996)][5] | $\mu_x = \mu_0$ (1-sample) |
| `mean1.2008SD`| [Srivastava and Du (2008)][6]  | $\mu_x = \mu_0$ (1-sample) |
| `mean2.1931Hotelling` | [Hotelling (1931)][3]       | $\mu_x = \mu_y$ (2-sample) |
| `mean2.1958Dempster`  | [Dempster (1958, 1960)][4]  | $\mu_x = \mu_y$ (2-sample) |
| `mean2.1965Yao`  | [Yao (1965)][7]  | $\mu_x = \mu_y$ (2-sample) |
| `mean2.1980Johansen`  | [Johansen (1980)][8]  | $\mu_x = \mu_y$ (2-sample) |
| `mean2.1986NVM` | [Nel and Van der Merwe (1986)][12] | $\mu_x = \mu_y$ (2-sample) |
| `mean2.1996BS`       | [Bai and Saranadasa (1996)][5] | $\mu_x = \mu_y$ (2-sample) |
| `mean2.2004KY`  | [Krishnamoorthy and Yu (2004)][9] | $\mu_x = \mu_y$ (2-sample) |
| `mean2.2008SD`| [Srivastava and Du (2008)][6]  | $\mu_x = \mu_y$ (2-sample) |
| `mean2.2011LJW`| [Lopes, Jacob, and Wainwright (2011)][13] | $\mu_x = \mu_y$ (2-sample) |
| `mean2.2014CLX` | [Cai, Liu, and Xia (2014)][14] | $\mu_x = \mu_y$ (2-sample) |
| `mean2.2014Thulin` | [Thulin (2014)][15] | $\mu_x = \mu_y$ (2-sample) |
| `meank.2009ZX` | [Zhang and Xu (2009)][16] | $\mu_1 = \cdots = \mu_k$ ($k$-sample) |
| `meank.2019CPH` | [Cao, Park, and He (2019)][11] | $\mu_1 = \cdots = \mu_k$ ($k$-sample) |



### 3. tests for variance $\sigma^2$
| function name | authors | description of $H_0$|
|---------------|------------------|:-------------------|
| `var1.chisq` | -        | $\sigma_x^2 ~\{\leq, =, \geq\}~ \sigma_0^2$ (1-sample) |
| `var2.F`     | -        | $\sigma_x^2 ~\{\leq, =, \geq\}~ \sigma_y^2$ (2-sample) |
| `vark.1937Bartlett` | [Bartlett (1937)][18] | $\sigma_1^2 = \cdots = \sigma_k^2$ ($k$-sample) |
| `vark.1960Levene`   | Levene (1960)   | $\sigma_1^2 = \cdots = \sigma_k^2$ ($k$-sample) |
| `vark.1974BF`    | [Brown and Forsythe (1974)][19] | $\sigma_1^2 = \cdots = \sigma_k^2$ ($k$-sample) |

### 4. tests for covariance $\Sigma$
| function name | authors | description of $H_0$|
|---------------|-----------------|:----------------|
| `cov1.2012Fisher`| [Fisher (2012)][30] | $\Sigma_x = \Sigma_0$ (1-sample) |
| `cov1.2015WL`    | [Wu and Li (2015)][31] | $\Sigma_x = \Sigma_0$ (1-sample) |
| `cov2.2012LC`    | [Li and Chen (2012)][10] | $\Sigma_x = \Sigma_y$ (2-sample) |
| `cov2.2013CLX`    | [Cai, Liu, and Xia (2013)][20] | $\Sigma_x = \Sigma_y$ (2-sample) |
| `cov2.2015WL`    | [Wu and Li (2015)][31] | $\Sigma_x = \Sigma_y$ (2-sample) |
| `covk.2001Schott`    | [Schott (2001)][21] | $\Sigma_1 = \cdots = \Sigma_k$ ($k$-sample) |
| `covk.2007Schott`    | [Schott (2007)][22] | $\Sigma_1 = \cdots = \Sigma_k$ ($k$-sample) |



### 5. simultaneous tests for mean $\mu$ and covariance $\Sigma$
| function name | authors | description of $H_0$|
|---------------|------------------------|:----------------|
| `sim1.2017Liu` | [Liu et al. (2017)][28] | $\mu_x = \mu_y,~\Sigma_x = \Sigma_y$ (1-sample) |
| `sim2.2018HN`  | [Hyodo and Nishiyama (2018)][29] | $\mu_x = \mu_y,~\Sigma_x = \Sigma_y$ (2-sample) |

### 6. tests for equality of distributions
| function name | authors | description of $H_0$|
|---------------|---------------------|:----------------|
| `eqdist.2014BG` | [Biswas and Ghosh (2014)][17] | $F_X = F_Y$ (2-sample) |

### 7. goodness-of-fit tests of normality
| function name | authors | description of $H_0$|
|---------------|------------------------|:----------------|
| `norm.1965SW` | [Shapiro and Wilk (1965)][23] | $F_X = \textrm{Normal} \in \mathbb{R}^1$|
| `norm.1972SF` | [Shapiro and Francia (1972)][26] | $F_X = \textrm{Normal} \in \mathbb{R}^1$|
| `norm.1980JB` | [Jarque and Bera (1980)][27] | $F_X = \textrm{Normal} \in \mathbb{R}^1$|
| `norm.1996AJB`| [Urzua (1996)][25] | $F_X = \textrm{Normal} \in \mathbb{R}^1$|
| `norm.2008RJB`| [Gel and Gastwirth (2008)][24] | $F_X = \textrm{Normal} \in \mathbb{R}^1$|

### 8. goodness-of-fit tests of uniformity
| function name | authors | description of $H_0$|
|---------------|------------------------|:----------------|
| `unif.2017YMi` | [Yang and Modarres (2017)][32] | $F_X = \textrm{Uniform} \in \mathbb{R}^p$ |
| `unif.2017YMq` | [Yang and Modarres (2017)][32] | $F_X = \textrm{Uniform} \in \mathbb{R}^p$ |

<!---
your comment goes here
and here
| `cov1.mxPBF`  | - | $\Sigma_x = \Sigma_0$ (1-sample) |
| `cov2.mxPBF`    | - | $\Sigma_x = \Sigma_y$ (2-sample) |
| `mean2.mxPBF` | - | $\mu_x = \mu_y$ (2-sample) |
-->

[32]: https://doi.org/10.1007/s00362-015-0715-x
[31]: https://arxiv.org/abs/1511.01611
[30]: https://doi.org/10.1016/j.jspi.2011.07.019
[28]: https://doi.org/10.1016/j.jspi.2017.03.009
[29]: https://doi.org/10.1007/s11749-017-0567-x
[23]: https://doi.org/10.1093/biomet/52.3-4.591
[24]: https://doi.org/10.1016/j.econlet.2007.05.022
[25]: https://doi.org/10.1016/S0165-1765(96)00923-8
[26]: https://doi.org/10.1080/01621459.1972.10481232
[27]: https://doi.org/10.1016/0165-1765(80)90024-5
[17]: https://doi.org/10.1016/j.jmva.2013.09.004
[10]: https://projecteuclid.org/euclid.aos/1338515142
[20]: https://doi.org/10.1080/01621459.2012.758041
[21]: https://doi.org/10.1016/j.csda.2007.03.004
[22]: https://doi.org/10.1016/j.csda.2007.03.004
[3]: https://projecteuclid.org/euclid.aoms/1177732979
[4]: https://projecteuclid.org/euclid.aoms/1177706437
[5]: http://www3.stat.sinica.edu.tw/statistica/j6n2/j6n21/j6n21.htm
[6]: https://doi.org/10.1016/j.jmva.2006.11.002
[7]: https://www.jstor.org/stable/2333819 
[8]: https://doi.org/10.1093/biomet/67.1.85
[9]: https://doi.org/10.1016/j.spl.2003.10.012
[11]: https://doi.org/10.1016/j.jspi.2018.12.002
[12]: https://doi.org/10.1080/03610928608829342
[13]: https://papers.nips.cc/paper/4260-a-more-powerful-two-sample-test-in-high-dimensions-using-random-projection
[14]: https://doi.org/10.1111/rssb.12034
[15]: https://doi.org/10.1016/j.csda.2013.12.003
[16]: https://doi.org/10.1007/s11425-009-0091-x
[1]: https://www.jstor.org/stable/2331554
[2]: https://doi.org/10.1093/biomet/34.1-2.28
[18]: https://doi.org/10.1098/rspa.1937.0109
[19]: https://www.jstor.org/stable/2285659 