// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_cov2_2012LC_biased_computeA
double cpp_cov2_2012LC_biased_computeA(arma::mat X);
RcppExport SEXP _SHT_cpp_cov2_2012LC_biased_computeA(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cov2_2012LC_biased_computeA(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cov2_2012LC_biased_computeC
double cpp_cov2_2012LC_biased_computeC(arma::mat X, arma::mat Y);
RcppExport SEXP _SHT_cpp_cov2_2012LC_biased_computeC(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cov2_2012LC_biased_computeC(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cov2_2012LC_computeA
double cpp_cov2_2012LC_computeA(arma::mat X);
RcppExport SEXP _SHT_cpp_cov2_2012LC_computeA(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cov2_2012LC_computeA(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cov2_2012LC_computeC
double cpp_cov2_2012LC_computeC(arma::mat X, arma::mat Y);
RcppExport SEXP _SHT_cpp_cov2_2012LC_computeC(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cov2_2012LC_computeC(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// adjust_clime
arma::mat adjust_clime(arma::mat omega);
RcppExport SEXP _SHT_adjust_clime(SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(adjust_clime(omega));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SHT_cpp_cov2_2012LC_biased_computeA", (DL_FUNC) &_SHT_cpp_cov2_2012LC_biased_computeA, 1},
    {"_SHT_cpp_cov2_2012LC_biased_computeC", (DL_FUNC) &_SHT_cpp_cov2_2012LC_biased_computeC, 2},
    {"_SHT_cpp_cov2_2012LC_computeA", (DL_FUNC) &_SHT_cpp_cov2_2012LC_computeA, 1},
    {"_SHT_cpp_cov2_2012LC_computeC", (DL_FUNC) &_SHT_cpp_cov2_2012LC_computeC, 2},
    {"_SHT_adjust_clime", (DL_FUNC) &_SHT_adjust_clime, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SHT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
