# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cov2_2012LC_biased_computeA <- function(X) {
    .Call('_SHT_cpp_cov2_2012LC_biased_computeA', PACKAGE = 'SHT', X)
}

cpp_cov2_2012LC_biased_computeC <- function(X, Y) {
    .Call('_SHT_cpp_cov2_2012LC_biased_computeC', PACKAGE = 'SHT', X, Y)
}

cpp_cov2_2012LC_computeA <- function(X) {
    .Call('_SHT_cpp_cov2_2012LC_computeA', PACKAGE = 'SHT', X)
}

cpp_cov2_2012LC_computeC <- function(X, Y) {
    .Call('_SHT_cpp_cov2_2012LC_computeC', PACKAGE = 'SHT', X, Y)
}

adjust_clime <- function(omega) {
    .Call('_SHT_adjust_clime', PACKAGE = 'SHT', omega)
}

