# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_variance <- function(x) {
    .Call('_SHT_cpp_variance', PACKAGE = 'SHT', x)
}

timesTwo <- function(x) {
    .Call('_SHT_timesTwo', PACKAGE = 'SHT', x)
}

